kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-api-configmap
  labels:
    prism: nginx-api-configmap
    name: nginx-api-configmap
data:
  api.conf: |
      server {
          listen 8080;

          server_name _;

          location / {
              try_files $uri $uri/ /index.html;
              add_header   Cache-Control public;
              expires      1d;
              root   /app;
          }

          location /api {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://api:8080/v1;
          }

          location /nbiaapi {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://nbia:8080/nbia-api;
          }

          location /coreapi {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://coreapi:8000/v1;
          }

          location /semapi {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://semapi:3000/v1;
          }
      }
  pathdb.conf: |
      server {
          listen 8080;

          server_name pathdb.*;

          location / {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://quip-pathdb:8080;
          }
      }
  nbia.conf: |
      server {
          listen 8080;

          server_name nbia.*;

          location / {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://nbia:8080;
          }
      }
  posda.conf: |
      server {
          listen 8080;

          server_name posda.*;

          location / {
             proxy_set_header X-Forwarded-Host $host;
             proxy_set_header X-Forwarded-Server $host;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_pass http://posdaweb:8080;
          }
      }
